# Generated by Django 4.1.6 on 2023-02-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='backgound_color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='activities',
            name='text_color',
            field=models.CharField(max_length=10),
        ),
    ]
