# Generated by Django 4.1.6 on 2023-02-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_activities_backgound_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='backgound_color',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='activities',
            name='text_color',
            field=models.CharField(max_length=9),
        ),
    ]
