# Generated by Django 4.1.6 on 2023-02-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_date_start_alter_events_date_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_stop',
            field=models.DateField(),
        ),
    ]
