# Generated by Django 4.1.6 on 2023-02-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_activities_backgound_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='backgound_color',
            new_name='background_color',
        ),
    ]
