# Generated by Django 4.1.7 on 2023-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_activities_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='displayed',
        ),
        migrations.AlterField(
            model_name='events',
            name='displayed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
