# Generated by Django 4.1.7 on 2023-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_activities_displayed_alter_events_displayed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='confirmed',
            field=models.BooleanField(),
        ),
    ]
