# Generated by Django 4.1.7 on 2023-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_events_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
