# Generated by Django 4.1.4 on 2022-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
