# Generated by Django 4.1.7 on 2023-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(2, 'Technician'), (4, 'Manager'), (6, 'Admin')], default=2),
        ),
    ]
